openapi: 3.0.0
info:
  title: Product Service API
  description: API for retrieving and managing products in AWS Lambda.
  version: 1.0.0
servers:
  - url: https://x6rf0rm2zi.execute-api.us-east-1.amazonaws.com/prod/
    description: AWS API Gateway Production URL

paths:
  /products:
    get:
      summary: Get a list of products
      description: Returns an array of available products.
      operationId: getProductsList
      responses:
        "200":
          description: Successful response with product list.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Internal Server Error
      tags:
        - Products

    post:
      summary: Create a new product
      description: Creates a new product with stock information.
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRequest"
      responses:
        "201":
          description: Product created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductResponse"
        "400":
          description: Invalid input data.
        "500":
          description: Internal Server Error.
      tags:
        - Products

  /products/{productId}:
    get:
      summary: Get product by ID
      description: Returns details of a single product based on its ID.
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve.
      responses:
        "200":
          description: Successful response with product details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found.
        "500":
          description: Internal Server Error.
      tags:
        - Products

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "229f24ab-2751-43db-9c63-d14e10d5b73d"
        title:
          type: string
          example: "Nutro Wholesome Essentials Natural Dry Cat Food"
        description:
          type: string
          example: "Made with real chicken and brown rice for a nutritious diet."
        price:
          type: number
          example: 21.99
        count:
          type: integer
          example: 5

    CreateProductRequest:
      type: object
      required:
        - title
        - price
        - count
      properties:
        title:
          type: string
          example: "Gaming Mouse"
        description:
          type: string
          example: "Ergonomic gaming mouse with RGB lighting."
        price:
          type: number
          example: 49.99
        count:
          type: integer
          example: 10

    CreateProductResponse:
      type: object
      properties:
        message:
          type: string
          example: "Product created successfully!"
        id:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
